/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://af5grwe3kbf3toh652wglf4qb4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "sendChefNotAPI",
            "endpoint": "https://asdiozu9m9.execute-api.eu-central-1.amazonaws.com/dev",
            "region": "eu-central-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-central-1:e5fbd6f3-bb21-4cf2-af01-3e0759845fe8",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_6ZTz9HkNm",
    "aws_user_pools_web_client_id": "68fjdlvn0ruino1ricgb711ca4",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "kfresh55f75eebccc943299bf3461169202604-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
